# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-07-15 18:29
from __future__ import unicode_literals

import cabot_alert_slack.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0009_slack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAlert',
            fields=[
                ('alertplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.AlertPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.alertplugin',),
        ),
        migrations.CreateModel(
            name='SlackAlertUserData',
            fields=[
                ('alertpluginuserdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.AlertPluginUserData')),
                ('slack_user_id_override', models.CharField(blank=True, help_text=b"Optional override for your SLack user ID. You only need to set this if your Cabot email does not match your Slack email. Enter 'ignore' to disable @mentions.", max_length=50, validators=[cabot_alert_slack.models.validate_slack_user_id])),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.alertpluginuserdata',),
        ),
    ]
