# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-08-09 20:16
from __future__ import unicode_literals

import cabot_alert_slack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabot_alert_slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackalertuserdata',
            name='slack_user_id_override',
            field=models.CharField(blank=True, help_text=b"Optional override for your Slack user ID. You only need to set this if your Cabot email does not match your Slack email. Enter 'ignore' to disable @mentions.", max_length=50, validators=[cabot_alert_slack.models.validate_slack_user_id]),
        ),
    ]
